server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/user/**
        - id: billing
          uri: lb://billing
          predicates:
            - Path=/billing/**

security:
  jwt:
    token:
      secret-key: 404E635266556A586E3272357538782F413F442A472D4B6150645367566B5970
