server:
  port: 9899

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Jahongir2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dadayevjahongir82@gmail.com
    password: {PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: 404E635266556A586E3272357538782F413F442A472D4B6150645367566B5970
      expiration-time: 3600000
  internal-username: internaluser@gmail.com