server:
  port: 9899

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
  instance:
    ip-address: ${DISCOVERY_HOST}

spring:
  application:
    name: auth
  mail:
    host: smtp.gmail.com
    port: 587
    username: dadayevjahongir82@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: 404E635266556A586E3272357538782F413F442A472D4B6150645367566B5970
      expiration-time: 3600000
  internal-username: internaluser@gmail.com