server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
  instance:
    ip-address: ${DISCOVERY_HOST}

spring:
  application:
    name: billing
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  internal-username: internaluser@gmail.com
